import React, { useMemo, useState } from 'react';
import { Header } from './Common';

export default function AdminView({navigate}:{navigate:(p:string)=>void}){
 const [authenticated,setAuthenticated]=useState(sessionStorage.getItem('comment-admin')==='1');const [password,setPassword]=useState('');const [count,setCount]=useState(1);const [days,setDays]=useState(15);const [quota,setQuota]=useState(200);const [codes,setCodes]=useState<string[]>(()=>JSON.parse(localStorage.getItem('comment-assistant-codes')||'[]'));
 const create=()=>{const fresh=Array.from({length:Math.min(100,count)},()=>`PY-${part()}-${part()}-${part()}`);const next=[...fresh,...codes];setCodes(next);localStorage.setItem('comment-assistant-codes',JSON.stringify(next))};
 if(!authenticated)return <div className="h-screen bg-gray-100"><Header title="管理员后台" onBack={()=>navigate('main')}/><div className="max-w-md mx-auto mt-24 bg-white rounded-xl p-8 shadow"><h2 className="text-xl font-bold mb-2">管理员登录</h2><p className="text-sm text-gray-500 mb-5">本地演示密码：admin。生产环境应由服务端环境变量校验。</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="input w-full mb-3" placeholder="管理员密码"/><button className="btn-primary w-full" onClick={()=>{if(password==='admin'){sessionStorage.setItem('comment-admin','1');setAuthenticated(true)}else alert('密码错误')}}>登录</button></div></div>;
 return <div className="h-screen bg-gray-100 flex flex-col"><Header title="管理员后台" onBack={()=>navigate('main')}/><main className="p-6 overflow-auto"><div className="grid grid-cols-[360px_1fr] gap-6"><section className="bg-white rounded-xl p-5 shadow-sm h-fit"><h2 className="font-bold text-lg mb-4">生成激活码</h2><Field label="生成数量"><input type="number" value={count} min="1" max="100" onChange={e=>setCount(Number(e.target.value))} className="input w-full"/></Field><Field label="有效天数"><input type="number" value={days} onChange={e=>setDays(Number(e.target.value))} className="input w-full"/></Field><Field label="AI 总次数"><input type="number" value={quota} onChange={e=>setQuota(Number(e.target.value))} className="input w-full"/></Field><button className="btn-primary w-full" onClick={create}>生成激活码</button><button className="tool w-full justify-center mt-2" onClick={()=>{const blob=new Blob([['激活码,有效天数,AI次数',...codes.map(c=>`${c},${days},${quota}`)].join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='激活码.csv';a.click()}}>导出 CSV</button></section><section className="bg-white rounded-xl shadow-sm overflow-hidden"><div className="p-5 border-b flex justify-between"><h2 className="font-bold text-lg">激活码列表</h2><span className="text-sm text-gray-400">共 {codes.length} 个</span></div><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">激活码</th><th>有效期</th><th>AI 配额</th><th>状态</th><th>操作</th></tr></thead><tbody>{codes.map(code=><tr key={code} className="border-t"><td className="p-3 font-mono">{code}</td><td className="text-center">{days} 天</td><td className="text-center">{quota}</td><td className="text-center text-green-600">未使用</td><td className="text-center"><button className="text-red-500" onClick={()=>{const next=codes.filter(c=>c!==code);setCodes(next);localStorage.setItem('comment-assistant-codes',JSON.stringify(next))}}>删除</button></td></tr>)}</tbody></table>{!codes.length&&<p className="p-12 text-center text-gray-400">尚未生成激活码</p>}</section></div></main></div>
}
function part(){return Math.random().toString(36).slice(2,6).toUpperCase()}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm mb-4"><span className="block text-gray-600 mb-1">{label}</span>{children}</label>}
