import React, { useEffect, useState } from 'react';
import { Header } from './Common';

type AdminCode={code:string;days:number;totalAiQuota:number;usedAiCount:number;remainingAiCount:number;deviceCount:number;maxDevices:number;createdAt:string;activatedAt?:string|null;expiresAt?:string|null;revoked:boolean;status:'unused'|'active'|'expired'|'revoked'};

export default function AdminView({navigate}:{navigate:(p:string)=>void}){
 const [authenticated,setAuthenticated]=useState(false);const [checking,setChecking]=useState(true);const [password,setPassword]=useState('');const [count,setCount]=useState(1);const [days,setDays]=useState(15);const [quota,setQuota]=useState(200);const [maxDevices,setMaxDevices]=useState(2);const [codes,setCodes]=useState<AdminCode[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const loadCodes=async()=>{const response=await fetch('/api/admin/codes');const result=await response.json().catch(()=>({}));if(!response.ok){setAuthenticated(false);throw new Error(result.error||'请重新登录')}setAuthenticated(true);setCodes(result.data?.codes||[])};
 useEffect(()=>{loadCodes().catch(()=>{}).finally(()=>setChecking(false))},[]);
 const login=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'登录失败');setPassword('');await loadCodes()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const create=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/codes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({count,days,quota,maxDevices})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'生成失败');await loadCodes()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const revoke=async(code:string)=>{if(!confirm(`确定作废激活码 ${code} 吗？`))return;const response=await fetch(`/api/admin/codes/${encodeURIComponent(code)}`,{method:'DELETE'});const result=await response.json().catch(()=>({}));if(!response.ok)return setError(result.error||'作废失败');await loadCodes()};
 const unbind=async(code:string)=>{if(!confirm(`确定解绑 ${code} 的全部浏览器吗？有效期和剩余次数将保留。`))return;const response=await fetch(`/api/admin/codes/${encodeURIComponent(code)}/unbind`,{method:'POST'});const result=await response.json().catch(()=>({}));if(!response.ok)return setError(result.error||'解绑失败');await loadCodes()};
 const logout=async()=>{await fetch('/api/admin/logout',{method:'POST'});setAuthenticated(false);setCodes([])};
 if(checking)return <div className="h-screen bg-gray-100"><Header title="管理员后台" onBack={()=>navigate('main')}/><p className="text-center mt-24 text-gray-500">正在验证管理员会话…</p></div>;
 if(!authenticated)return <div className="h-screen bg-gray-100"><Header title="管理员后台" onBack={()=>navigate('main')}/><div className="max-w-md mx-auto mt-24 bg-white rounded-xl p-8 shadow"><h2 className="text-xl font-bold mb-2">管理员登录</h2><p className="text-sm text-gray-500 mb-5">请输入服务器环境变量 ADMIN_PASSWORD 配置的密码。</p><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()} className="input w-full mb-3" placeholder="管理员密码"/>{error&&<p className="text-sm text-red-500 mb-3">{error}</p>}<button disabled={loading||!password} className="btn-primary w-full" onClick={login}>{loading?'登录中…':'登录'}</button></div></div>;
 return <div className="h-screen bg-gray-100 flex flex-col"><Header title="管理员后台" onBack={()=>navigate('main')}/><main className="p-6 overflow-auto"><div className="flex justify-end mb-3"><button className="tool" onClick={logout}>退出管理员</button></div><div className="grid grid-cols-[360px_1fr] gap-6"><section className="bg-white rounded-xl p-5 shadow-sm h-fit"><h2 className="font-bold text-lg mb-4">生成激活码</h2><Field label="生成数量"><input type="number" value={count} min="1" max="100" onChange={e=>setCount(Number(e.target.value))} className="input w-full"/></Field><Field label="有效天数"><input type="number" value={days} min="1" max="3650" onChange={e=>setDays(Number(e.target.value))} className="input w-full"/></Field><Field label="AI 总次数"><input type="number" value={quota} min="1" onChange={e=>setQuota(Number(e.target.value))} className="input w-full"/></Field><Field label="允许浏览器数"><input type="number" value={maxDevices} min="1" max="10" onChange={e=>setMaxDevices(Number(e.target.value))} className="input w-full"/></Field>{error&&<p className="text-sm text-red-500 mb-3">{error}</p>}<button disabled={loading} className="btn-primary w-full" onClick={create}>{loading?'生成中…':'生成激活码'}</button><button className="tool w-full justify-center mt-2" onClick={()=>exportCsv(codes)}>导出 CSV</button></section><section className="bg-white rounded-xl shadow-sm overflow-hidden"><div className="p-5 border-b flex justify-between"><h2 className="font-bold text-lg">激活码列表</h2><span className="text-sm text-gray-400">共 {codes.length} 个</span></div><div className="overflow-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">激活码</th><th>有效期</th><th>AI 使用</th><th>设备</th><th>状态</th><th>操作</th></tr></thead><tbody>{codes.map(item=><tr key={item.code} className="border-t"><td className="p-3 font-mono">{item.code}</td><td className="text-center">{item.expiresAt?item.expiresAt.slice(0,10):`${item.days} 天（激活后）`}</td><td className="text-center">{item.usedAiCount} / {item.totalAiQuota}</td><td className="text-center text-xs text-gray-500">{item.deviceCount} / {item.maxDevices}</td><td className={`text-center ${item.status==='active'?'text-green-600':item.status==='unused'?'text-blue-600':'text-red-500'}`}>{statusText(item.status)}</td><td className="text-center"><div className="flex justify-center gap-3"><button disabled={!item.deviceCount||item.revoked} className="text-blue-600" onClick={()=>unbind(item.code)}>解绑设备</button><button disabled={item.revoked} className="text-red-500" onClick={()=>revoke(item.code)}>作废</button></div></td></tr>)}</tbody></table></div>{!codes.length&&<p className="p-12 text-center text-gray-400">尚未生成激活码</p>}</section></div></main></div>
}
function statusText(status:AdminCode['status']){return {unused:'未使用',active:'使用中',expired:'已过期',revoked:'已作废'}[status]}
function exportCsv(codes:AdminCode[]){const lines=['激活码,有效天数,AI总次数,已使用,剩余次数,已绑定浏览器,允许浏览器,状态',...codes.map(c=>`${c.code},${c.days},${c.totalAiQuota},${c.usedAiCount},${c.remainingAiCount},${c.deviceCount},${c.maxDevices},${statusText(c.status)}`)];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='激活码.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm mb-4"><span className="block text-gray-600 mb-1">{label}</span>{children}</label>}
