import React, { useMemo, useState } from 'react';
import { Search, Zap, Sparkles, RefreshCw, Copy, Trash2, Lock, Unlock, History, Check, X } from 'lucide-react';
import { Header } from './Common';
import { TAG_CATEGORIES } from '../data';
import { useApp } from '../store';
import type { Student, TagKey } from '../types';

export default function AugmentedView({navigate}:{navigate:(p:string)=>void}){
 const app=useApp(); const {students,activeStudentId,setActiveStudentId,updateStudent,toggleTag,generate,runAi,restoreHistory,setToast}=app;
 const [search,setSearch]=useState('');const [filter,setFilter]=useState('全部');const [tone,setTone]=useState('温和鼓励');const [target,setTarget]=useState(150);const [loading,setLoading]=useState('');
 const current=students.find(s=>s.id===activeStudentId)||students[0];
 const list=useMemo(()=>students.filter(s=>s.name.includes(search)&&(filter==='全部'||(filter==='未生成'&&!s.comment)||(filter==='已生成'&&s.comment)||(filter==='已锁定'&&s.locked))),[students,search,filter]);
 if(!current)return <div className="h-screen flex items-center justify-center">暂无学生，<button className="text-blue-600" onClick={()=>navigate('main')}>返回添加</button></div>;
 const ai=async(mode:'polish'|'rewrite')=>{setLoading(mode);try{await runAi(current.id,mode,tone,target);setToast(mode==='polish'?'AI 润色完成':'AI 重写完成')}catch(e){setToast((e as Error).message)}finally{setLoading('')}};
 const keys:TagKey[]=['learning','personality','behavior','specialty','improvement','suggestion'];
 return <div className="h-screen min-w-[1200px] flex flex-col bg-gray-100 overflow-hidden"><Header title="AI 增强视图" onBack={()=>navigate('main')}/><div className="flex-1 grid grid-cols-[300px_1fr_1.15fr] overflow-hidden">
  <aside className="bg-white border-r flex flex-col"><div className="p-4 border-b"><h2 className="font-bold mb-3">学生列表区</h2><div className="relative"><Search size={15} className="absolute left-3 top-2.5"/><input aria-label="搜索学生姓名" className="input pl-9 w-full" placeholder="搜索学生姓名" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="flex gap-2 mt-3">{['全部','未生成','已生成','已锁定'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`mini-tab ${filter===x?'active':''}`}>{x}</button>)}</div><p className="text-xs text-gray-400 mt-3">共 {students.length} 人，已生成 {students.filter(s=>s.comment).length} 人</p></div><div className="overflow-auto">{list.map(s=><button key={s.id} onClick={()=>setActiveStudentId(s.id)} className={`w-full text-left p-4 border-b hover:bg-blue-50 ${s.id===current.id?'bg-blue-50 border-l-4 border-l-blue-500':''}`}><div className="flex justify-between"><b>{s.no} {s.name}</b><span className="text-xs text-gray-400">{s.locked?'已锁定':s.comment?'已生成':'未生成'}</span></div><p className="text-xs text-gray-500 mt-2 line-clamp-2">{s.comment||'暂无评语'}</p></button>)}</div></aside>
  <section className="bg-white border-r overflow-auto"><div className="p-4 border-b sticky top-0 bg-white z-10"><h2 className="font-bold">学生标签与信息区</h2></div><div className="p-6"><h3 className="text-2xl font-bold mb-5">{current.name}</h3><div className="grid grid-cols-2 gap-4"><Field label="学生类型"><select disabled={current.locked} value={current.type} onChange={e=>updateStudent(current.id,{type:e.target.value as Student['type']})} className="input w-full"><option>优秀生</option><option>中等生</option><option>后进生</option><option>未分类</option></select></Field><Field label="性别"><select disabled={current.locked} value={current.gender} onChange={e=>updateStudent(current.id,{gender:e.target.value as Student['gender']})} className="input w-full"><option>男</option><option>女</option><option>未知</option></select></Field></div><Field label="补充说明"><textarea disabled={current.locked} value={current.note} onChange={e=>updateStudent(current.id,{note:e.target.value})} className="input w-full h-20 resize-none" placeholder="老师可输入补充说明"/></Field>
    <div className="flex justify-between items-center mt-6 mb-2"><h4 className="font-bold">表现标签</h4><button disabled={current.locked} onClick={()=>updateStudent(current.id,{tags:{learning:[],personality:[],behavior:[],specialty:[],improvement:[],suggestion:[]}})} className="text-xs text-red-500">清空标签</button></div>{keys.map(k=><div key={k} className="py-3 border-b"><p className="text-sm font-medium mb-2">{TAG_CATEGORIES[k].title}</p><div className="flex flex-wrap gap-2">{TAG_CATEGORIES[k].tags.map(t=><button disabled={current.locked} key={t} onClick={()=>toggleTag(current.id,k,t)} className={`tag-choice ${current.tags[k].includes(t)?'selected':''}`}>{current.tags[k].includes(t)&&<Check size={12}/>} {t}</button>)}</div></div>)}
  </div></section>
  <section className="bg-white overflow-auto"><div className="p-4 border-b sticky top-0 bg-white z-10"><h2 className="font-bold">评语编辑与 AI 操作区</h2></div><div className="p-6"><div className="flex items-center justify-between mb-2"><span className="status">{current.locked?'已锁定':current.status==='empty'?'未生成':current.status==='ai_polished'?'AI润色':current.status==='ai_rewritten'?'AI重写':'已生成'}</span><span className="text-xs text-gray-400">{current.comment.length} 字</span></div><textarea aria-label="评语编辑器" disabled={current.locked} value={current.comment} onChange={e=>updateStudent(current.id,{comment:e.target.value,status:e.target.value?'edited':'empty'},'manual')} className="w-full h-64 border rounded-lg p-4 leading-7 resize-none disabled:bg-gray-100" placeholder="在这里生成或编辑评语..."/><div className="grid grid-cols-3 gap-2 mt-3"><Action label="规则生成" icon={<Zap/>} onClick={()=>{generate([current.id],target);setToast('基础评语已生成')}} disabled={current.locked}/><Action label={loading==='polish'?'润色中…':'AI 润色'} icon={<Sparkles/>} onClick={()=>ai('polish')} disabled={current.locked||!!loading}/><Action label={loading==='rewrite'?'重写中…':'AI 重写'} icon={<RefreshCw/>} onClick={()=>ai('rewrite')} disabled={current.locked||!!loading}/><Action label="复制评语" icon={<Copy/>} onClick={()=>navigator.clipboard.writeText(current.comment).then(()=>setToast('已复制'))}/><Action label={current.locked?'解锁':'锁定'} icon={current.locked?<Unlock/>:<Lock/>} onClick={()=>updateStudent(current.id,{locked:!current.locked,status:!current.locked?'locked':current.comment?'edited':'empty'})}/><Action label="清空评语" icon={<Trash2/>} onClick={()=>!current.locked&&confirm('确定清空当前评语吗？')&&updateStudent(current.id,{comment:'',status:'empty'})} danger/></div>
    <div className="bg-gray-50 rounded-lg p-4 mt-6"><h3 className="font-bold mb-3">AI 设置</h3><div className="grid grid-cols-2 gap-4"><Field label="语气"><select value={tone} onChange={e=>setTone(e.target.value)} className="input w-full"><option>温和鼓励</option><option>正式稳重</option><option>亲切自然</option><option>更像老师写的</option></select></Field><Field label="目标字数"><select value={target} onChange={e=>setTarget(Number(e.target.value))} className="input w-full"><option value={100}>100 字左右</option><option value={150}>150 字左右</option><option value={200}>200 字左右</option></select></Field></div></div>
    <div className="mt-6"><h3 className="font-bold mb-3 flex items-center gap-2"><History size={16}/>历史版本</h3><div className="space-y-2 max-h-60 overflow-auto">{[...current.history].reverse().map((h,i)=><div key={h.id} className="border rounded p-3 text-sm"><div className="flex justify-between mb-2"><span className="text-xs text-blue-600">{h.type==='base'?'基础版':h.type==='ai_polish'?'AI 润色版':h.type==='ai_rewrite'?'AI 重写版':'手动编辑版'}</span><span className="text-xs text-gray-400">{new Date(h.createdAt).toLocaleString()}</span></div><p className="text-gray-600 line-clamp-2">{h.content}</p><button disabled={current.locked} onClick={()=>restoreHistory(current.id,h.content)} className="text-blue-600 text-xs mt-2">恢复此版本</button></div>)}{!current.history.length&&<p className="text-sm text-gray-400 border-2 border-dashed rounded p-6 text-center">尚无历史版本</p>}</div></div>
  </div></section>
 </div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm text-gray-600 mb-4"><span className="block mb-1.5">{label}</span>{children}</label>}
function Action({label,icon,onClick,disabled,danger}:{label:string;icon:React.ReactNode;onClick:()=>void;disabled?:boolean;danger?:boolean}){return <button disabled={disabled} onClick={onClick} className={`row-btn py-2.5 ${danger?'text-red-600':''}`}>{React.isValidElement(icon)&&React.cloneElement(icon as React.ReactElement<{size:number}>,{size:15})}{label}</button>}
