import React, { useMemo, useRef, useState } from 'react';
import { Download, Upload, UserPlus, Zap, Eraser, Trash2, Printer, FileSpreadsheet, FileText, Search, Lock, Unlock, Copy, Sparkles, RefreshCw, Cloud, WandSparkles, DatabaseBackup } from 'lucide-react';
import { Header, Modal } from './Common';
import { TAG_CATEGORIES } from '../data';
import { createStudent } from '../data';
import { useApp } from '../store';
import type { Student, TagKey } from '../types';
import { downloadTemplate, exportExcel, exportProject, exportWord, importStudents, readProject } from '../io';

export default function MainView({navigate}:{navigate:(page:string)=>void}) {
  const app=useApp(); const {students,setStudents,selectedIds,setSelectedIds,updateStudent,deleteStudents,toggleTag,generate,runAi,setToast,activation,showStudentName,setShowStudentName}=app;
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('全部状态'); const [type,setType]=useState('全部类型');
  const [addOpen,setAddOpen]=useState(false); const [activationOpen,setActivationOpen]=useState(false); const [newName,setNewName]=useState(''); const [newGender,setNewGender]=useState<Student['gender']>('未知'); const [newType,setNewType]=useState<Student['type']>('未分类'); const [loading,setLoading]=useState('');
  const [tagPicker,setTagPicker]=useState<{studentId:string;category:TagKey}|null>(null);
  const importRef=useRef<HTMLInputElement>(null); const projectRef=useRef<HTMLInputElement>(null);
  const filtered=useMemo(()=>students.filter(s=>s.name.includes(search)&&(type==='全部类型'||s.type===type)&&(status==='全部状态'||(status==='未生成'&&!s.comment)||(status==='已生成'&&!!s.comment)||(status==='AI润色'&&s.status==='ai_polished')||(status==='已锁定'&&s.locked))),[students,search,status,type]);
  const selected=students.filter(s=>selectedIds.includes(s.id));
  const act=async(id:string,action:string)=>{const s=students.find(x=>x.id===id);if(!s)return;try{
    if(action==='generate'){generate([id]);setToast('已生成基础评语');}
    if(action==='polish'||action==='rewrite'){setLoading(`${id}-${action}`);await runAi(id,action as 'polish'|'rewrite');setToast(action==='polish'?'AI 润色完成':'AI 重写完成');}
    if(action==='copy'){await navigator.clipboard.writeText(s.comment);setToast('评语已复制');}
    if(action==='lock')updateStudent(id,{locked:!s.locked,status:!s.locked?'locked':s.comment?'edited':'empty'});
    if(action==='delete'&&confirm(`确定删除 ${s.name} 吗？`))deleteStudents([id]);
  }catch(e){setToast((e as Error).message)}finally{setLoading('')}};
  const bulkAi=async(mode:'polish'|'rewrite')=>{const targets=selected.filter(s=>s.comment&&!s.locked);if(!targets.length)return setToast('请选择有评语且未锁定的学生');if(targets.length>activation.remainingAiCount)return setToast('AI 剩余次数不足');if(!confirm(`将处理 ${targets.length} 名学生，预计消耗 ${targets.length} 次，是否继续？`))return;setLoading(`bulk-${mode}`);let done=0;for(const s of targets){try{await runAi(s.id,mode);done++}catch{break}}setLoading('');setToast(`批量处理完成：${done}/${targets.length}`)};
  const onImport=async(file?:File)=>{if(!file)return;setLoading('import');try{const incoming=await importStudents(file,students.length);const names=new Set(students.map(s=>s.name));const unique=incoming.filter(s=>!names.has(s.name));setStudents(p=>[...p,...unique]);setToast(`成功导入 ${unique.length} 人，跳过重复 ${incoming.length-unique.length} 人`)}catch{setToast('文件解析失败，请使用模板格式')}finally{setLoading('')}};
  const onProject=async(file?:File)=>{if(!file)return;try{const data=await readProject(file);if(Array.isArray(data.students)){setStudents(data.students);setToast('项目数据已恢复')}else setToast('项目文件格式不正确')}catch{setToast('项目文件读取失败')}};
  const generateAll=()=>{const has=students.some(s=>s.comment&&!s.locked);if(has&&!confirm('部分学生已有评语，是否覆盖未锁定学生？'))return;const r=generate(students.map(s=>s.id));setToast(`生成完成：成功 ${r.success} 人，跳过 ${r.skipped} 人`)};
  const clearTags=(ids:string[])=>{if(!confirm('确定清空所选学生标签吗？锁定学生不会受影响。'))return;setStudents(prev=>prev.map(s=>ids.includes(s.id)&&!s.locked?{...s,tags:{learning:[],personality:[],behavior:[],specialty:[],improvement:[],suggestion:[]}}:s));setToast('标签已清空')};
  return <div className="flex flex-col h-screen bg-[#F4F5F7] text-gray-800 min-w-[1280px] overflow-hidden">
    <Header/><div className="flex items-center gap-2 px-5 py-3 bg-[#F8F9FB] border-b flex-wrap">
      <Tool icon={<Download/>} label="下载模板" onClick={downloadTemplate}/><Tool icon={<Upload/>} label={loading==='import'?'导入中…':'导入名单'} onClick={()=>importRef.current?.click()}/><input ref={importRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>onImport(e.target.files?.[0])}/>
      <Tool icon={<UserPlus/>} label="添加学生" green onClick={()=>setAddOpen(true)}/><button onClick={generateAll} className="tool-primary"><Zap size={16}/>一键生成全部</button><Tool icon={<WandSparkles/>} label="AI 增强视图" onClick={()=>navigate('augmented')}/>
      <Tool icon={<Eraser/>} label="清空所有标签" onClick={()=>clearTags(students.map(s=>s.id))}/><Tool icon={<Trash2/>} label="删除所有学生" danger onClick={()=>confirm('确定删除所有未锁定学生吗？')&&deleteStudents(students.filter(s=>!s.locked).map(s=>s.id))}/>
      <div className="ml-auto flex gap-2"><Tool icon={<Printer/>} label="排版打印PDF" onClick={()=>navigate('export-pdf')}/><Tool icon={<FileSpreadsheet/>} label="导出 Excel" green onClick={()=>exportExcel(students)}/><Tool icon={<FileText/>} label="导出 Word" onClick={()=>{const n=students.filter(s=>!s.comment).length;if(!n||confirm(`有 ${n} 名学生尚未生成，是否继续导出？`))exportWord(students)}}/><Tool icon={<DatabaseBackup/>} label="项目备份" onClick={()=>exportProject({students,activation})}/><Tool icon={<Upload/>} label="恢复项目" onClick={()=>projectRef.current?.click()}/><input ref={projectRef} hidden type="file" accept=".json" onChange={e=>onProject(e.target.files?.[0])}/><button onClick={()=>setActivationOpen(true)} className="tool">激活码</button></div>
    </div>
    <main className="flex-1 overflow-auto p-5"><div className="bg-white rounded-lg shadow-sm border overflow-hidden min-h-full"><div className="flex items-center gap-6 p-4 border-b sticky left-0 bg-white"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16}/><input aria-label="按姓名搜索学生" value={search} onChange={e=>setSearch(e.target.value)} placeholder="按姓名搜索学生..." className="input w-60" style={{paddingLeft:'2.5rem'}}/></div><label className="filter">状态筛选：<select value={status} onChange={e=>setStatus(e.target.value)} className="input"><option>全部状态</option><option>未生成</option><option>已生成</option><option>AI润色</option><option>已锁定</option></select></label><label className="filter">类型筛选：<select value={type} onChange={e=>setType(e.target.value)} className="input"><option>全部类型</option><option>优秀生</option><option>中等生</option><option>后进生</option><option>未分类</option></select></label><label className="filter gap-2 whitespace-nowrap"><input aria-label="显示学生名称" type="checkbox" checked={showStudentName} onChange={e=>setShowStudentName(e.target.checked)}/>显示学生名称</label><span className="ml-auto text-sm text-gray-500">显示 {filtered.length} / {students.length} 人</span></div>
      <table className="w-full min-w-[1500px] table-fixed text-sm"><thead className="bg-gray-50"><tr><th className="w-10"><input aria-label="全选学生" type="checkbox" checked={filtered.length>0&&filtered.every(s=>selectedIds.includes(s.id))} onChange={e=>setSelectedIds(e.target.checked?[...new Set([...selectedIds,...filtered.map(s=>s.id)])]:selectedIds.filter(id=>!filtered.some(s=>s.id===id)))}/></th>{['序号','姓名','性别','类型','学习表现','性格品质','行为习惯','特长/建议','生成的评语','操作'].map(h=><th key={h} className={`p-3 text-left ${h==='序号'?'w-14':h==='姓名'?'w-24':h==='性别'?'w-20':h==='类型'?'w-24':h==='生成的评语'?'w-[330px]':h==='操作'?'w-[190px]':'w-36'}`}>{h}</th>)}</tr></thead>
      <tbody>{filtered.map(s=><StudentRow key={s.id} s={s} selected={selectedIds.includes(s.id)} toggleSelect={()=>setSelectedIds(p=>p.includes(s.id)?p.filter(x=>x!==s.id):[...p,s.id])} updateStudent={updateStudent} toggleTag={toggleTag} openPicker={(category)=>setTagPicker({studentId:s.id,category})} act={act} loading={loading}/>)}</tbody></table>
    </div></main>
    {selected.length>0&&<div className="absolute bottom-11 left-0 right-0 bg-blue-50 border-t border-blue-200 px-6 py-3 flex gap-4 items-center text-sm shadow"><span>已选择 <b className="text-blue-600">{selected.length}</b> 位学生</span><button onClick={()=>{const r=generate(selectedIds);setToast(`已生成 ${r.success} 人`)}}>批量生成</button><button disabled={!!loading} onClick={()=>bulkAi('polish')}>{loading==='bulk-polish'?'处理中…':'批量 AI 润色'}</button><button onClick={()=>bulkAi('rewrite')}>批量 AI 重写</button><button onClick={()=>clearTags(selectedIds)}>批量清空标签</button><button className="text-red-600" onClick={()=>confirm('确定删除所选学生吗？')&&deleteStudents(selectedIds)}>批量删除</button><button className="ml-auto" onClick={()=>setSelectedIds([])}>取消选择</button></div>}
    <footer className="bg-[#F4F5F7] px-6 py-3 text-xs text-gray-500 flex justify-between"><span className="flex gap-2"><Cloud size={15}/>数据已自动保存到本地，请勿随意清理浏览器缓存。</span><span>学生 {students.length} 人 · 已生成 {students.filter(s=>s.comment).length} 人 · 已锁定 {students.filter(s=>s.locked).length} 人</span></footer>
    {addOpen&&<Modal title="添加学生" onClose={()=>setAddOpen(false)}><div className="space-y-4"><label className="block text-sm">姓名<input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} className="input mt-1 w-full"/></label><label className="block text-sm">性别<select value={newGender} onChange={e=>setNewGender(e.target.value as Student['gender'])} className="input mt-1 w-full"><option>未知</option><option>男</option><option>女</option></select></label><label className="block text-sm">类型<select value={newType} onChange={e=>setNewType(e.target.value as Student['type'])} className="input mt-1 w-full"><option>未分类</option><option>优秀生</option><option>中等生</option><option>后进生</option></select></label><button className="btn-primary w-full" onClick={()=>{if(!newName.trim())return;app.addStudent(createStudent(newName.trim(),students.length,{type:newType,gender:newGender}));setNewName('');setNewGender('未知');setAddOpen(false);setToast('学生已添加')}}>确认添加</button></div></Modal>}
    {activationOpen&&<ActivationModal onClose={()=>setActivationOpen(false)}/>} 
    {tagPicker&&<TagPicker studentId={tagPicker.studentId} category={tagPicker.category} onClose={()=>setTagPicker(null)}/>} 
  </div>;
}

function StudentRow({s,selected,toggleSelect,updateStudent,toggleTag,openPicker,act,loading}:{s:Student;selected:boolean;toggleSelect:()=>void;updateStudent:any;toggleTag:any;openPicker:(category:TagKey)=>void;act:any;loading:string}){
 const cats:TagKey[]=['learning','personality','behavior','specialty'];
 return <tr className={`border-t align-top ${selected?'bg-blue-50/70 ring-1 ring-inset ring-blue-300':'hover:bg-gray-50'}`}><td className="p-4 text-center"><input aria-label={`选择 ${s.name}`} type="checkbox" checked={selected} onChange={toggleSelect}/></td><td className="p-2 text-center">{s.no}</td><td className="p-3 font-medium">{s.name}</td><td className="p-2"><select aria-label={`${s.name}性别`} disabled={s.locked} value={s.gender} onChange={e=>updateStudent(s.id,{gender:e.target.value})} className="bg-transparent w-full"><option>男</option><option>女</option><option>未知</option></select></td><td className="p-3"><select disabled={s.locked} value={s.type} onChange={e=>updateStudent(s.id,{type:e.target.value})} className="bg-transparent"><option>优秀生</option><option>中等生</option><option>后进生</option><option>未分类</option></select></td>{cats.map(k=><td className="p-2" key={k}><div className="flex flex-wrap gap-1">{s.tags[k].map(t=><button disabled={s.locked} key={t} onClick={()=>toggleTag(s.id,k,t)} className="tag">{t} ×</button>)}</div><button aria-label={`${s.name}${TAG_CATEGORIES[k].title}多选标签`} disabled={s.locked} onClick={()=>openPicker(k)} className="mt-2 text-xs text-blue-600 border border-dashed border-blue-300 rounded px-2 py-1 hover:bg-blue-50">＋ 多选标签</button></td>)}<td className="p-3">{s.motto&&<div className="text-xs text-red-500 font-bold mb-1 px-1">盼你：{s.motto}</div>}<textarea aria-label={`${s.name}的评语`} disabled={s.locked} value={s.comment} onChange={e=>updateStudent(s.id,{comment:e.target.value,status:e.target.value?'edited':'empty'},'manual')} placeholder="等待生成评语..." className="w-full h-24 resize-none border rounded p-2 disabled:bg-gray-100"/><span className="status">{s.locked?'已锁定':s.status==='empty'?'未生成':s.status==='ai_polished'?'AI润色':s.status==='ai_rewritten'?'AI重写':s.status==='edited'?'手动编辑':'已生成'}</span></td><td className="p-3"><div className="grid grid-cols-2 gap-2"><RowBtn label="生成" icon={<Zap/>} disabled={s.locked} onClick={()=>act(s.id,'generate')}/><RowBtn label={loading===`${s.id}-polish`?'处理中':'AI润色'} icon={<Sparkles/>} disabled={s.locked||!!loading} onClick={()=>act(s.id,'polish')}/><RowBtn label="AI重写" icon={<RefreshCw/>} disabled={s.locked||!!loading} onClick={()=>act(s.id,'rewrite')}/><RowBtn label="复制" icon={<Copy/>} onClick={()=>act(s.id,'copy')}/><RowBtn label={s.locked?'解锁':'锁定'} icon={s.locked?<Lock/>:<Unlock/>} onClick={()=>act(s.id,'lock')}/><RowBtn label="删除" icon={<Trash2/>} danger onClick={()=>act(s.id,'delete')}/></div></td></tr>
}
function RowBtn({label,icon,onClick,disabled,danger}:{label:string;icon:React.ReactNode;onClick:()=>void;disabled?:boolean;danger?:boolean}){return <button disabled={disabled} onClick={onClick} className={`row-btn ${danger?'text-red-600 bg-red-50':''}`}>{React.isValidElement(icon)&&React.cloneElement(icon as React.ReactElement<{size:number}>,{size:13})}{label}</button>}
function Tool({icon,label,onClick,green,danger}:{icon?:React.ReactNode;label:string;onClick:()=>void;green?:boolean;danger?:boolean}){return <button onClick={onClick} className={`tool ${green?'text-green-600':''} ${danger?'text-red-600 bg-red-50':''}`}>{React.isValidElement(icon)&&React.cloneElement(icon as React.ReactElement<{size:number}>,{size:16})}{label}</button>}
function ActivationModal({onClose}:{onClose:()=>void}){const {activation,activate,setToast}=useApp();const [code,setCode]=useState(activation.code);return <Modal title="激活产品" onClose={onClose}><p className="text-sm text-gray-500 mb-3">请输入管理员发放的激活码。演示码：PY-DEMO-2026-LOCAL</p><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} className="input w-full mb-3"/><button className="btn-primary w-full" onClick={()=>{const ok=activate(code.trim());setToast(ok?'激活成功':'激活码不存在或不可用');if(ok)onClose()}}>验证激活码</button></Modal>}
function TagPicker({studentId,category,onClose}:{studentId:string;category:TagKey;onClose:()=>void}){const {students,toggleTag,updateStudent}=useApp();const student=students.find(s=>s.id===studentId);if(!student)return null;const options=TAG_CATEGORIES[category].tags;const selected=student.tags[category];const presets:Record<string,string[]>={优秀生:options.slice(0,4),中等生:options.slice(1,4),后进生:[...options.slice(1,2),...options.slice(-3)],未分类:[]};return <Modal title={`${student.name} · ${TAG_CATEGORIES[category].title}（可连续多选）`} onClose={onClose}><div className="flex items-center justify-between mb-4"><span className="text-sm text-gray-500">已选择 {selected.length} 项</span><div className="flex gap-3 text-xs"><button className="text-blue-600" onClick={()=>updateStudent(studentId,{tags:{...student.tags,[category]:[...options]}})}>全选</button><button className="text-amber-600" onClick={()=>updateStudent(studentId,{tags:{...student.tags,[category]:presets[student.type]}})}>推荐组合</button><button className="text-red-500" onClick={()=>updateStudent(studentId,{tags:{...student.tags,[category]:[]}})}>清空</button></div></div><div className="grid grid-cols-2 gap-2">{options.map(tag=><button key={tag} onClick={()=>toggleTag(studentId,category,tag)} className={`flex items-center justify-between rounded-lg border px-3 py-2.5 text-sm ${selected.includes(tag)?'bg-blue-50 border-blue-400 text-blue-700':'bg-white border-gray-200 hover:border-blue-300'}`}><span>{tag}</span><span className={`w-5 h-5 rounded border flex items-center justify-center ${selected.includes(tag)?'bg-blue-500 text-white border-blue-500':'border-gray-300'}`}>{selected.includes(tag)?'✓':''}</span></button>)}</div><button className="btn-primary w-full mt-5" onClick={onClose}>完成选择</button></Modal>}
